#
# Travis CI job configuration for the Yawg project.
#
# https://travis-ci.org/
#
---

language: java

jdk:
  - openjdk8

script:
  - ./devtools/bin/build-travisci-job --run

cache:
  directories:
    - $HOME/.m2
    - $HOME/.yawgdevtools

addons:
  apt:
    packages:
      - graphviz
      - xsltproc

after_success:
  - bash <(curl -s https://codecov.io/bash)


#
# Preparation for uploading changes to the Yawg site.
#
before_deploy:
  - eval "$(ssh-agent -s)"
  - openssl aes-256-cbc -K $encrypted_9f5a14dc3874_key -iv $encrypted_9f5a14dc3874_iv -in ./devtools/conf/id_rsa-travisci.enc -out ./devtools/conf/id_rsa-travisci -d
  - chmod 600 ./devtools/conf/id_rsa-travisci
  - ssh-add ./devtools/conf/id_rsa-travisci

#
# Bakes a new release of the Yawg site and uploads the changes to the
# GitHub pages repo.
#
deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: script
  script: ./devtools/bin/build-site --yawg-install-root=$HOME/.yawgdevtools --upload
