/**************************************************************************
 *
 * Copyright (c) 2016 Yawg project contributors.
 *
 **************************************************************************/

package com.varmateo.yawg.asciidoctor;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;
import java.util.Optional;

import org.asciidoctor.Asciidoctor;
import org.asciidoctor.AttributesBuilder;
import org.asciidoctor.OptionsBuilder;
import org.asciidoctor.SafeMode;
import org.asciidoctor.ast.Author;
import org.asciidoctor.ast.DocumentHeader;
import org.asciidoctor.internal.AsciidoctorCoreException;

import com.varmateo.yawg.PageContext;
import com.varmateo.yawg.TemplateDataModel;

import com.varmateo.yawg.commons.util.Lists;
import com.varmateo.yawg.util.FileUtils;


/**
 *
 */
/* package private */ final class AsciidoctorBakerDataModelBuilder {


    private final Asciidoctor _asciidoctor;


    /**
     *
     */
    AsciidoctorBakerDataModelBuilder(final Asciidoctor asciidoctor) {

        _asciidoctor = asciidoctor;
    }


    /**
     *
     */
    public TemplateDataModel build(
            final Path sourcePath,
            final Path targetDir,
            final Path targetPath,
            final PageContext context)
            throws AsciidoctorCoreException, IOException {

        String sourceContent = FileUtils.readAsString(sourcePath);
        AttributesBuilder attributes = buildAttributes(sourcePath, targetDir);
        OptionsBuilder options =
                OptionsBuilder.options()
                .attributes(attributes)
                .headerFooter(false)
                .safe(SafeMode.UNSAFE);
        String body = _asciidoctor.render(sourceContent, options);
        String pageUrl = context.getDirUrl() + "/" + targetPath.getFileName();
        DocumentHeader header = _asciidoctor.readDocumentHeader(sourceContent);
        String title =
                Optional.ofNullable(header)
                .map(h -> h.getDocumentTitle())
                .map(t -> t.getMain())
                .orElseGet(() -> FileUtils.basename(sourcePath));

        TemplateDataModel.Builder modelBuilder =
                TemplateDataModel.builder()
                .setTitle(title)
                .setBody(body)
                .setPageUrl(pageUrl)
                .setRootRelativeUrl(context.getRootRelativeUrl())
                .setPageVars(context.getPageVars());
        buildAuthors(modelBuilder, header);

        TemplateDataModel result = modelBuilder.build();

        return result;
    }


    /**
     *
     */
    private void buildAuthors(
            final TemplateDataModel.Builder modelBuilder,
            final DocumentHeader header) {

        List<Author> authors = header.getAuthors();

        // This convoluted logic is needed because
        // DocumentHeader.getAuthor(), DocumentHeader.getAuthors() do
        // not behave consistently with each other.

        if ( !authors.isEmpty() ) {
            Lists.forEach(
                    authors,
                    a -> modelBuilder.addAuthor(a.getFullName(), a.getEmail()));
        } else {
            Author singleAuthor = header.getAuthor();

            if ( (singleAuthor!=null) && (singleAuthor.getFullName()!=null) )  {
                modelBuilder.addAuthor(
                        singleAuthor.getFullName(),
                        singleAuthor.getEmail());
            }
        }
    }


    /**
     * Prepares a set of attributes that affect how Asciidoctor works.
     */
    private AttributesBuilder buildAttributes(
            final Path sourcePath,
            final Path targetDir) {

        AttributesBuilder attributes = AttributesBuilder.attributes();

        // Path of directory that contains the document. It is needed
        // for the PlantUML AsciidoctorJ extension to find its input
        // files relative to the AsciiDoc source document.
        attributes.attribute("docdir", sourcePath.getParent().toString());

        // Path of directory where image files generated by PlantUML
        // will be created.
        String imagesOutDir = targetDir.toAbsolutePath().normalize().toString();
        attributes.attribute("imagesoutdir", imagesOutDir);

        // Enable basic syntax highlithing by default.
        attributes.attribute("source-highlighter", "coderay");
        attributes.attribute("coderay-css", "style");

        return attributes;
    }


}
