= Creating a release of the Yawg software
:author: Jorge Nunes
:toc:
:sectnums:





== Introduction

The steps for making a an official release of the Yawg softare are
enumerated below.

* Validate the desired version number

* Create release Git tag.

* Create release tarball and deploy to
  http://central.sonatype.org/pages/ossrh-guide.html[Open Source
  Software Repository Hosting] (OSSRH) Maven staging repo.

* Upload release tarball to Github.

* Release OSSRH staging repo to Maven central.

The following sections describe with more detail what needs to be done
in each step. The commands shown in the text assume your working area
reflects the `HEAD` of the `main` branch.





== Validate desired version number

Ensure the desired version number is defined at
`conf/yawg-defaults.conf`.

If you do make changes on `conf/yawg-defaults.conf` you will need to:

* Run `devtools/bin/build-sync-version` to update the version number
  in all relevant locations.

* Commit and push your changes to the Github repo.

* Initiate the release process from the beginning.





== Create release Git tag

The Git tag will mark the commit used for the release in the project
change history.

The release Git tag is to be created at the HEAD of the master
branch. Do it like this:

[source,sh,subs=attributes+]
----
git tag -a v{latestYawgVersion} -m "Version {latestYawgVersion}"
git push origin v{latestYawgVersion}
----





== Create release tarball and deploy to OSSRH Maven staging repo

This step is composed of two actions:

* Create a release tarball. The tarball will be named
  `yawg-{latestYawgVersion}.tar.bz2`, and it will be created at the root of
  your working area.

* Upload Maven artifacts to the
  http://central.sonatype.org/pages/ossrh-guide.html[OSSRH] Maven
  staging repository. These Maven artifacts include the JARs and
  Javadocs of the Yawg libraries that are needed to integrate Yawg in
  other products.


To execute the two actions mentioned above the following command is
used:

[source,sh]
----
./devtools/bin/build-bundle --release
----





== Upload release tarball to Github

The release tarball will be hosted at Github. This is the simplest
solution for making the release tarball accessible for download.

Go to https://github.com/jorgefranconunes/yawg/releases and create a
release:

* With the tag created before.

* With the tarball manually created in the previous section.





== Release OSSRH staging repo to Maven central

The actions described in this section follow the
http://central.sonatype.org/pages/releasing-the-deployment.html[instructions
from Sonatype] for OSSRH.

* Go to https://oss.sonatype.org/ and login.

* Look for the latest staging repository with a name starting with
  `comvarmateo`.

* Check that the contents of that staging repository appear to be
  fine.

* Click the `Close` action for the repository. This will prepare the
  staging repository for being copied to Maven Central.

* Click the `Release` action for the repository. This will copy the
  staging repository to Maven Central. This process can take some
  minutes to complete. You can confirm the process has completed by
  checking on Maven Central at
  https://repo1.maven.org/maven2/com/varmateo/yawg/yawg-api/ that the
  new version is there.
