= Developers


Here you will find information intended for the developers of the Yawg
project.





== Code quality

image:https://travis-ci.org/jorgefranconunes/yawg.svg?branch=master["Build Status", link="https://travis-ci.org/jorgefranconunes/yawg"]
image:https://codecov.io/gh/jorgefranconunes/yawg/branch/master/graph/badge.svg[codecov, link="https://codecov.io/gh/jorgefranconunes/yawg"]
image:https://api.codacy.com/project/badge/Grade/5a8509efe93441eaafc869854e8a5dcf["Codacy code quality", link="https://www.codacy.com/app/jorgefranconunes/yawg?utm_source=github.com&utm_medium=referral&utm_content=jorgefranconunes/yawg&utm_campaign=Badge_Grade"]
image:https://img.shields.io/maven-central/v/com.varmateo.yawg/yawg-api.svg["Maven Central", link="https://repo1.maven.org/maven2/com/varmateo/yawg/yawg-api/"]
image:http://www.javadoc.io/badge/com.varmateo.yawg/yawg-api.svg["Javadocs", link="http://www.javadoc.io/doc/com.varmateo.yawg/yawg-api"]
image:https://img.shields.io/badge/License-GPL%20v3-blue.svg["License: GPL v3", link="https://www.gnu.org/licenses/gpl-3.0"]


link:CodeQualityReports/index.html[Code quality reports] - Maven
generated reports for the latest commit in the `master` branch.





== Instructions

link:DevEnvSetup.html[Setting up the development environment]

link:CreatingRelease.html[Creating a release of the Yawg software]





== Operations

link:DeployingMavenArtifacts.html[Deploying to Maven Central] -- Notes
on deploying Maven artifacts to the Maven Central repository.

link:PublishingYawgSite.html[Publishing the Yawg site]





== Third party services

The Yawg project makes use of some third-party services freely
available to open source projects.

https://www.codacy.com/"[Codacy] -- Automated code review tool for
monitoring technical debt, and help improve code quality.

https://codecov.io/gh/jorgefranconunes/yawg[Codecov] -- Project trends
in code coverage.

https://github.com/jorgefranconunes/yawg[GitHub] -- Git repository
hosting and issue management.

https://oss.sonatype.org/[Sonatype OSSRH] -- Repository hosting
service for open source project binaries.

https://travis-ci.org/jorgefranconunes/yawg[Travis CI] -- Automated
build and test service.
