#
#
#

template: "yawg-site.ftlh"

#
# List of globs for files NOT to be included in the bake. This list is
# tipically very similar to the .gitignore list.
#
exclude:
  - "*~"
  - "*.~"
  - "*.aux"
  - "*.bak"
  - "*.log"
  - "*.out"
  - "*.pid"
  - "target"
  - "work"
  - ".*~$"
  - ".yawg.yml"
  - ".travis.yml"
  - ".gitignore"


pageVars:
  navbarSelectedItem: "home"


pageVarsHere:
  breadcrumb:
    title: "Home"
    url: "index.html"

