#
#
#

#
# Default template for the all pages in the Yawg site.
#
template: "yawg-site.ftlh"

#
# The home page uses a dedicated template.
#
templatesHere:
  "yawg-site-notitle.ftlh":
    - "index.html"

#
# List of globs for files NOT to be included in the bake. This list
# should tipically be very similar to the .gitignore list.
#
exclude:
  - "*~"
  - "*.~"
  - ".*~$"
  - "*.aux"
  - "*.bak"
  - ".github"
  - ".gitignore"
  - "*.log"
  - "*.out"
  - "*.pid"
  - "target"
  - "work"
  - ".yawg.yml"


pageVars:
  latestYawgVersion: "1.0.0"
  navbarSelectedItem: "home"


pageVarsHere:
  breadcrumb:
    title: "Home"
    url: "index.html"

#
# Include static assets (CSS, images).
#
extraDirsHere:
  - "../assets"
