#
#
#

template: "yawg-site.ftlh"

exclude:
  - "*~"
  - "*.~"
  - "*.aux"
  - "*.bak"
  - "*.log"
  - "*.out"
  - "*.pid"
  - "target"
  - "work"
  - ".*~$"
  - ".yawg.yml"
  - ".travis.yml"
  - ".gitignore"


pageVars:
  navbarSelectedItem: "home"


pageVarsHere:
  breadcrumb:
    title: "Home"
    url: "index.html"

