#
#
#

ignore:
  - "*~"
  - "*.~"
  - "*.aux"
  - "*.bak"
  - "*.log"
  - "*.out"
  - "*.pid"
  - "target"
  - "work"
  - ".*~$"
  - ".yawg.yml"


templateVars:
  navbarSelectedItem: "home"
  
  breadcrumb:
    title: "Home"
    url: "index.html"
