= YAWG - Yet Another Wiki Generator : There and back
:author: Jorge Nunes





Products in the same area as Yawg:

* http://awestruct.org/[Awestruct]

* http://jbake.org/[JBake]

* http://jekyllrb.com/[Jekyll]





== YawgBaker

Performs the generation of the site from the input source.

Configuration:

* Source directory - Each file from the input directory will be copied
  to the target directory. The directory structure will be preserved
  on the target directory. Each file can also potentially be
  transformed.

* Target directory - Root directory where all files originating from
  the source and resources directories will be copied to.

* Resources directory - Directory whose contents will be copied as is
  to the target directory.





== Third-party libraries

The implementation makes use of the libraries enumerated below.

* https://commons.apache.org/proper/commons-cli/[Apache Commons CLI] -
  API for parsing command line options.

* https://github.com/asciidoctor/asciidoctorj[AsciidoctorJ] - Java
  bindings for http://asciidoctor.org/[Asciidoctor]. Used for
  converting Asciidoc documents to
  HTML. http://www.javadoc.io/doc/org.asciidoctor/asciidoctorj/1.5.4[Javadoc].

* http://freemarker.org/[Apache Freemarker] - Template engine. Used
  for generating the final HTML pages from the intermediate HTML
  output by AsccidoctorJ. http://freemarker.org/docs/api/[Javadoc].

* http://jsoup.org/[jsoup] - Java HTML parser. Used for kneading HTML
  input for the final bake.





== Documentation look & feel

* http://getmdl.io/[Material Design Lite] - Material Design look and
  feel from Google.
