= YAWG User Guide
:author: Jorge Nunes





Welcome to the user manual for Yawg.

TBD - What is Yawg?

TBD - Who is this document intended to?

TBD - How is this document organized?





== Requirements

You will need Java 8 to run Yawg.

TBD - More requirements? E.g. Linux environment.





== Download

TBD - Where can I download Yawg from?





== Installing Yawg

Unpack the Yawg tarball wherever it suits you. An example follows:

----
mkdir ~/local
curl https://github.com/jorgefranconunes/yawg/somewhere/yawg-1.0.0.tar.gz \
    | tar xfz -C ~/local
----

The example above will have installed Yawg under `$HOME/local/yawg-1.1.0/`.

Installation tree.

----
yawg-1.1.0/
    +-- bin
    +-- conf
    +-- doc
    +-- lib
----

There is no need to ever change any of the files under the
installation directory.





== Running Yawg

The command line tool to bake sites is at `bin/yawg` under the
installation tree.

TBD - What does the `yawg` tool do?

You need Java 8 to run Yawg. You have two different ways to select
which JVM should be used for running Yawg.

* If the environment variable `JAVA_HOME` is defined, it will be used
  to select the JVM.

* If the environment variable `JAVA_HOME` is not defined, then Yawg
  will attemp to look for `java` according to the PATH envionrment
  variable.

* If the two previous bullets to not apply, then `yawg` will refuse to
  work and just print a failure message informing you of the error in
  your ways.

If you run `yawg` it without any arguments it will just print some
information on how to use the tool, and will then exit.

----
Yawg 1.0.0 - CLI Baker
Copyright (c) 2016 Jorge Nunes

Usage: yawg [OPTION] ...

Bakes a site from a directory tree.
 
Options:
    --assets <PATH>      path of assets directory
 -h,--help               show this help text and exit
    --source <PATH>      path of source directory
    --target <PATH>      path of target directory
    --templates <PATH>   path of templates directory
 -v,--version            show version and exit
    --verbose            show abundant logging
----

The `yawg` command supports the following command line options:

`--assets <PATH>` -- Path to the assets directory. The contents of
this directory will be recursively copied to the target directory. The
files under the assets directory are copied without any
transformations.

`--source <PATH>` -- Path to the directory containing the content to
be baked.

`--target <PATH>` -- Path to the directory where the results of the
baked will be copied to. If this directory does not yet exist, it will
be created.

`--templates <PATH>` -- Path the directory containing the page templates
that may be used during the baking.





== Baker types

There are three types of baker.

* Asciidoc -- Converts input files in Asciidoc format to HTML.

* HTML -- Converts an input file in HTML format to another HTML file
  generated by the selected page template.

* Copy -- Just copies the input file to the target directory without
  making any change.





== Configuring the baking process

A set of baking parameters can be used to influence the baking
process. Each directory under the source directory being baked can
specify its own set of baking parameters.

The baking parameters are defined in a file named `.yawg.yaml` inside
each directory. The existence of the `.yawg.yaml` file is optional. If
there is no `.yawg.yaml` file in a given directory, then the baking
parameters for the parent directory will be used instead.

The `.yawg.yaml` file, as you might have guessed, is in
http://yaml.org/[YAML] format.

The supported baking parameters are listed below.

`template` (`String`) -- The name of the page template to use for
baking the files in the directory. If not specified it will default to
`default.ftlh`.

`filesToIgnore` (`List<String>`) -- List of regular expressions
representing the files in the directory that are to be ignore during
the bake.

`filesToIncludeOnly` (`List<String>`) -- List of regular expressions
representing the files in the directory that are to be baked. All
other files in the directory will be skipped. This parameter takes
precedence over the `filesToIgnore` parameter.





== Page templates

Yawg supports http://freemarker.org/[Freemarker] page templates.

The page template files are read from the directory specified with the
`--templates` command line option.

TBD -- More info on page templates.





=== Page template data model

The page template has access to a set of variables while it is being
processed during the baking of a document. We call data model to the
set of variables accessible to the page template.

The variables composing the data model are described below.

`body` -- String containing the raw HTML resulting from converting the
source document into HTML. This is an HTML snippet ready to be
included a `<body>` element, or any other block level element.

`productName` -- The name of the Yawg softare (i.e. "Yawg"). The value
of the template variable is always the same.

`title` -- The document title. If the source document did not define a
title, then the base name of the source document file will be used as
title.

`version` -- The version of the Yawg software. The value of the
template variable is always the same, for a given Yawg release.

