<#-- Template for the footer block. -->

<footer class="yawg-footer">
  <p>&copy;2016 Yawg project contributors</p>
  <p>
    Mixed with
    <a href="http://getbootstrap.com/" target="_blank">Bootstrap 3.3.6</a>
    |
    Baked with
    <a href="http://yawg.varmateo.com/">${yawg.productName} ${yawg.version}</a>
    |
    <a href="${yawg.rootRelativeUrl}/Acknowledgements.html">Acknowledgements</a>
  </p>
</footer>
