[[sec-PageTemplates]]
== Page templates

Yawg supports http://freemarker.org/[Freemarker] page templates.

The page template files are read from the directory specified with the
`--templates` command line option.

The page template has access to a set of variables while it is being
processed during the baking of a document. We call data model to the
set of variables accessible to the page template.

The variables composing the data model are described below.

* `yawg.bakeId` -- Unique bake ID. Each bake will have a different
  identifier.

* `yawg.body` -- String containing the raw HTML resulting from
  converting the source document into HTML. This is an HTML snippet
  ready to be included in a `<body>` element, or any other block level
  element.

* `yawg.pageUrl` -- The URL of the page being baked relative to the
  top URL of the baked site.

* `yawg.productName` -- The name of the Yawg software
  (i.e. "Yawg"). The value of this template variable is always the
  same, for a given Yawg release.

* `yawg.rootRelativeUrl` -- The relative URL for the top URL of the
  baked site. Useful for refering to resources at the top of the
  document tree.

* `yawg.title` -- The document title. If the source document did not
  define a title, then the base name of the source document file will
  be used as title.

* `yawg.version` -- The version of the Yawg software. The value of
  this template variable is always the same, for a given Yawg release.
