= Yawg User Guide
:author: Jorge Nunes
:toc:
:sectnums:





This is the user guide for Yawg. Yawg is a static site
generator. Given a source directory tree with files, a new directory
tree will be populated with HTML files generated from the baking of
the source files. Yawg is able to bake files in AsciiDoc and HTML
formats. Other types of files will just be copied without any
modification.

This document is intended for end users.

The remainder of this document is organized as follows:

* <<sec-Requirements>> -- Describes the pre-requisites needed for
  installing and running Yawg.

* <<sec-DownloadAndInstall>> -- Provides instructions on installing
  the Yawg software.

* <<sec-Running>> -- Shows you how to run Yawg and describes the
  command line options.

* <<sec-BakerTypes>> -- Introduces you to the currently supported
  baker types: AsciiDoc, and HTML. The type of baker used defines how
  a given source file will be baked.

* <<sec-ConfiguringBaking>> -- Describes how the baking process can be
  configured per-directory. For example, which template to use, or
  which files should be ignored.

* <<sec-PageTemplates>> -- Describes how templates are used for the
  rendering of the final HTML. This section also addresses the data
  model the template has access to for injecting data into the
  generated HTML.





include::UserGuide-Requirements.adoc[]

include::UserGuide-DownloadAndInstall.adoc[]

include::UserGuide-Running.adoc[]

include::UserGuide-BakerTypes.adoc[]

include::UserGuide-ConfiguringBaking.adoc[]

include::UserGuide-PageTemplates.adoc[]
